keys:
  - &homelab age1wyqx305ug088r9qjdskzyhfscpspmhhfuq96hwwr32zpsjlme35qd72l5n # Your public key from step 1
creation_rules:
  - path_regex: secrets\.yaml$
    key_groups:
      - age:
          - *homelab
